# Generated by Django 3.1.1 on 2021-03-08 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biker', '0003_auto_20210307_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='verify_vehicle',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biker.verifyvehicle'),
        ),
    ]
