# Generated by Django 3.1.7 on 2021-03-26 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biker', '0004_auto_20210308_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='biker',
            name='email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biker',
            name='password',
            field=models.TextField(blank=True, null=True),
        ),
    ]
