# Generated by Django 3.1.7 on 2021-04-13 05:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20210405_0217'),
        ('biker', '0006_auto_20210329_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biker',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.user'),
        ),
        migrations.AlterField(
            model_name='path',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Path_created_by', to='customer.user'),
        ),
        migrations.AlterField(
            model_name='path',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Path_last_updated_by', to='customer.user'),
        ),
        migrations.AlterField(
            model_name='point',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Point_created_by', to='customer.user'),
        ),
        migrations.AlterField(
            model_name='point',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Point_last_updated_by', to='customer.user'),
        ),
        migrations.AlterField(
            model_name='route',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Route_created_by', to='customer.user'),
        ),
        migrations.AlterField(
            model_name='route',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Route_last_updated_by', to='customer.user'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Vehicle_created_by', to='customer.user'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Vehicle_last_updated_by', to='customer.user'),
        ),
        migrations.AlterField(
            model_name='verifyvehicle',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='VerifyVehicle_created_by', to='customer.user'),
        ),
        migrations.AlterField(
            model_name='verifyvehicle',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='VerifyVehicle_last_updated_by', to='customer.user'),
        ),
        migrations.CreateModel(
            name='BikerHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_lng', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('origin_lat', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('destination_lng', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('destination_lat', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('address_origin', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('address_destination', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('isRideConfirmed', models.BooleanField(default=False)),
                ('isRideCancelled', models.BooleanField(default=False)),
                ('_id', models.CharField(max_length=20)),
                ('_v', models.CharField(max_length=20)),
                ('price', models.IntegerField(default=0)),
                ('rideHash', models.CharField(max_length=20)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('biker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BikerHistory_biker', to='customer.user')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BikerHistory_customer', to='customer.user')),
            ],
        ),
    ]
