# Generated by Django 3.1.7 on 2021-04-13 08:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20210405_0217'),
        ('biker', '0008_auto_20210413_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikerlog',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='BikerLog_created_by', to='customer.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bikerlog',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bikerlog',
            name='_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bikerlog',
            name='_v',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bikerlog',
            name='address_destination',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='bikerlog',
            name='address_origin',
            field=models.TextField(),
        ),
    ]
