# Generated by Django 3.1.7 on 2021-04-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biker', '0009_auto_20210413_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikerlog',
            name='_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bikerlog',
            name='_v',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bikerlog',
            name='rideHash',
            field=models.TextField(),
        ),
    ]
