# Generated by Django 3.1.7 on 2021-04-15 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biker', '0010_auto_20210413_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bikerlog',
            old_name='isRideCancelled',
            new_name='is_ride_cancelled',
        ),
        migrations.RenameField(
            model_name='bikerlog',
            old_name='isRideConfirmed',
            new_name='is_ride_confirmed',
        ),
        migrations.RenameField(
            model_name='bikerlog',
            old_name='rideHash',
            new_name='ride_hash',
        ),
    ]
