# Generated by Django 3.1.7 on 2021-04-16 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20210405_0217'),
        ('biker', '0011_auto_20210415_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikerlog',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BikerLog_created_by', to='customer.user'),
        ),
    ]
