# Generated by Django 3.1.1 on 2021-05-14 23:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('biker', '0013_auto_20210423_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewBikerLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('comment', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('biker_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biker.bikerlog')),
            ],
        ),
    ]
