# Generated by Django 3.1.7 on 2021-04-19 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20210405_0217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='encoded_password',
        ),
    ]
