# Generated by Django 3.1.1 on 2021-05-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_auto_20210515_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='point_accumulation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='level',
            name='point_condition',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='PointOfMoney',
        ),
    ]
