# Generated by Django 3.1.1 on 2021-05-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_auto_20210515_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpoint',
            name='point',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
